routes/web.php
<?php

use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::group([
        'prefix' => 'admin',
        'namespace'=>'Admin'
    ], function() {
    Route::resource('clientes','ClientesController');
});


Auth::routes();

Route::group([
    'prefix' => '/login',
    'namespace'=>'Auth'
], function() {
        Route::post('/social','LoginController@loginSocial')->name('login.social');
        Route::get('/callback','LoginController@loginCallback');
});
Route::get('/home', 'HomeController@index')->name('home');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    const TYPE_INDIVIDUAL = 'individual';
    const TYPE_LEGAL = 'legal';
    const MARITAL_STATUS = [
        1   => 'Solteiro',
        2   => 'Casado',
        3   => 'Divorciado'
    ];
    protected  $fillable = [
        'name',
        'document_number',
        'email',
        'phone',
        'defaulter',
        'date_birth',
        'sex',
        'marital_status',
        'company_name',
        'physical_disability',
        'cliente_type'
    ];
    public static function getClientType($type){
        return $type == Cliente::TYPE_LEGAL ? $type : Cliente::TYPE_INDIVIDUAL;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use \App\Notifications\MyResetPasswordNotification;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new MyResetPasswordNotification($token));
    }
}

app/helpers.php
<?php

function layout(){
    return \Request::is('admin/*')?'layouts.admin':'layouts.app';
}

app/Http/Controllers/Admin/ClientesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use \App\Http\Requests\ClienteStoreRequest;
use App\Http\Controllers\Controller;
use App\Cliente;

class ClientesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $pesquisa = $request->input('pesquisa');
        $clients_query = \App\Cliente::where(function($q) use($pesquisa){
            $q->where('name', 'like', '%'.$pesquisa.'%');
            $q->orWhere('email', 'like', '%'.$pesquisa.'%');
        });
        $clients = $clients_query->paginate(2);
        return view('admin.clientes.index',['clientes'=>$clients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
      
        
        return view('admin.clientes.create',['cliente'=>new Cliente(),'cliente_type' =>Cliente::getClientType($request->cliente_type)]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store( ClienteStoreRequest $request)
    {
        $data = $request->all();
        $data['defaulter'] = $request->has('defaulter');
        $data['cliente_type'] = Cliente::getClientType($request->cliente_type);
        Cliente::create($data);
        return redirect()->route('clientes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $cliente
     * @return \Illuminate\Http\Response
     */
    public function show(Cliente $cliente)
    {
        return view('admin.clientes.show',['cliente'=>$cliente]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $cliente
     * @return \Illuminate\Http\Response
     */
    public function edit(Cliente $cliente)
    {
        $cliente = Cliente::findOrFail($cliente->id);
        
        return view('admin.clientes.edit',['cliente' =>$cliente,'cliente_type' =>Cliente::getClientType($cliente->cliente_type)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ClienteStoreRequest $request, Cliente $cliente)
    {
        
        $cliente = Cliente::findOrFail($cliente->id);
        $data = $request->all();
        $data['defaulter'] = $request->has('defaulter');
        $cliente->fill($data);
        $cliente->save();
        return redirect()->route('clientes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $cliente
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cliente $cliente)
    {
        $cliente->delete();
        return redirect()->route('clientes.index');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GitHubController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Laravel\Socialite\Facades\Socialite;

class GitHubController extends Controller
{
    public function redirect()
    {
        return Socialite::driver('github')->redirect();
    }
    public function handle()
    {
       $user =  Socialite::driver('github')->user();
       dd($user);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/clientes/_form.blade.php
@csrf
<input type="hidden" name="cliente_type" value="{{$cliente_type}}">
<div class="form-group">
    <label for="name">Nome</label>
    <input class="form-control" id="name" name="name" value="{{old('name',$cliente->name)}}">
</div>

<div class="form-group">
    <label for="document_number">Documento</label>
    <input class="form-control" id="document_number" name="document_number" value="{{old('document_number',$cliente->document_number)}}">
</div>

<div class="form-group">
    <label for="email">E-mail</label>
    <input class="form-control" id="email" name="email" type="email" value="{{old('email',$cliente->email)}}">
</div>

<div class="form-group">
    <label for="phone">Telefone</label>
    <input class="form-control" id="phone" name="phone" value="{{old('phone',$cliente->phone)}}">
</div>
@if($cliente_type == \App\Cliente::TYPE_INDIVIDUAL)
    @php
        $marital_status = $cliente->marital_status;

    @endphp

    <div class="form-group">
        <label for="marital_status">Estado Civil</label>
        <select class="form-control" name="marital_status" id="marital_status" value="{{$marital_status}}">
            <option value="">Selecione o estado civil</option>
            <option value="1" {{old('marital_status',$marital_status) == 1?'selected="selected"':''}}>Solteiro</option>
            <option value="2" {{old('marital_status',$marital_status) == 2?'selected="selected"':''}}>Casado</option>
            <option value="3" {{old('marital_status',$marital_status) == 3?'selected="selected"':''}}>Divorciado
            </option>
        </select>
    </div>
        <div class="form-group">
            <label for="date_birth">Data Nasc.</label>
            <input class="form-control" id="date_birth" name="date_birth" type="date" value="{{old('date_birth',$cliente->date_birth)}}">
        </div>
        @php
            $sex  =$cliente->sex;
        @endphp
        <div class="radio">
            <label>
                <input type="radio" name="sex" value="m" {{old('sex',$sex) == 'm'?'checked="checked"':''}}> Masculino
            </label>
        </div>

        <div class="radio">
            <label>
                <input type="radio" name="sex" value="f" {{old('sex',$sex) == 'f'?'checked="checked"':''}}> Feminino
            </label>
        </div>

        <div class="form-group">
            <label for="physical_disability">Deficiência Física</label>
            <input class="form-control" id="physical_disability" name="physical_disability" value="{{old('physical_disability',$cliente->physical_disability)}}">
        </div>   
@else
    <div class="form-group">
        <label for="company_name">Nome Fantasia</label>
        <input class="form-control" id="company_name" name="company_name" value="{{old('company_name',$cliente->company_name)}}">
    </div>
@endif
<div class="checkbox">
    <label>
        <input id="defaulter" name="defaulter" type="checkbox" {{old('defaulter',$cliente->defaulter)?'checked="checked"':''}}>
        Inadimplente?
    </label>
</div>

resources/views/admin/clientes/create.blade.php
@extends('layouts.layout')

@section('content')

<div class="container">
    <h3>Novo cliente</h3>
    <h4>{{$cliente_type == \App\Cliente::TYPE_INDIVIDUAL? 'Pessoa Física': 'Pessoa Jurídica'}}</h4>
    <a href="{{route('clientes.create',['cliente_type' => \App\Cliente::TYPE_INDIVIDUAL])}}">Pessoa Física</a> |
    <a href="{{route('clientes.create',['cliente_type' => \App\Cliente::TYPE_LEGAL])}}">Pessoa Jurídica</a>
</div>
    
   @include('admin.form._form_errors')
    
    <div class="container">
        <form method="post" action="{{ route('clientes.store') }}">
            @include('admin.clientes._form')
            <button type="submit" class="btn btn-default">Criar</button>
         </form>
    </div>
    
@endsection

resources/views/admin/clientes/edit.blade.php
@extends('layouts.layout')

@section('content')
<div class="container">
    <h3>Editar cliente</h3>
    @include('admin.form._form_errors')
    <form method="post" action="{{ route('clientes.update',['cliente' => $cliente->id]) }}">
        <input type="hidden" name="id" value="{{$cliente->id}}">
        {{method_field('PUT')}}
            @include('admin.clientes._form')
        <button type="submit" class="btn btn-default">Salvar</button>
    </form>
@endsection
</div>
   

resources/views/admin/clientes/index.blade.php
@extends('layouts.layout')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md text-center">
            <h3>Listagem de clientes {{$clientes->total()}}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md text-center">
            <a class="btn btn-primary" href="{{ route('clientes.create') }}">Criar novo</a>
        </div>
    </div>
</div>
<div class="container-fluid mt-2">
    <form action="" method="get">
        <input type="search" name="pesquisa" value="{{@$_GET['pesquisa']}}">
        <button type="submit">Buscar</button>
    </form>
    <div class="row">
        {{$clientes->appends(['busca' => @$_GET['busca'], 'pesquisa'=> @$_GET['pesquisa']])->links()}}
            <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>CNPJ/CPF</th>
                        <th>Data Nasc.</th>
                        <th>E-mail</th>
                        <th>Telefone</th>
                        <th>Sexo</th>
                        <th>Ação</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($clientes as $client)
                        <tr>
                            <td>{{ $client->id }}</td>
                            <td>{{ $client->name }}</td>
                            <td>{{ $client->document_number }}</td>
                            <td>{{ $client->date_birth }}</td>
                            <td>{{ $client->email }}</td>
                            <td>{{ $client->phone }}</td>
                            <td>{{ $client->sex }}</td>
                            <td>
                                <a href="{{route('clientes.edit',['client' => $client->id])}}">Editar</a> |
                                <a href="{{route('clientes.show',['client' => $client->id])}}">Ver</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                @endsection
            
    </div>
</div>
    
    

resources/views/admin/clientes/show.blade.php
@extends('layouts.layout')

@section('content')
    <h3>Ver cliente</h3>
    <a class="btn btn-primary" href="{{ route('clientes.edit',['cliente' => $cliente->id]) }}">Editar</a>
    <a class="btn btn-danger" href="{{ route('clientes.destroy',['cliente' => $cliente->id]) }}"
        onclick="event.preventDefault();
        if(confirm('Deseja excluir este item?')){document.getElementById('form-delete').submit();}">Excluir</a>
    <form id="form-delete"style="display: none" action="{{ route('clientes.destroy',['cliente' => $cliente->id]) }}" method="post">
        {{csrf_field()}}
        {{method_field('DELETE')}}
    </form>
    <br/><br/>
    <table class="table table-bordered">
        <tbody>
        <tr>
            <th scope="row">ID</th>
            <td>{{$cliente->id}}</td>
        </tr>
        <tr>
            <th scope="row">Nome</th>
            <td>{{$cliente->name}}</td>
        </tr>
        <tr>
            <th scope="row">Documento</th>
            <td>{{$cliente->document_number}}</td>
        </tr>
        <tr>
            <th scope="row">E-mail</th>
            <td>{{$cliente->email}}</td>
        </tr>
        <tr>
            <th scope="row">Telefone</th>
            <td>{{$cliente->phone}}</td>
        </tr>
        <tr>
            <th scope="row">Estado Civil</th>
            <td>
                @switch($cliente->marital_status)
                    @case(1)
                        Solteiro
                        @break

                    @case(2)
                        Casado
                        @break

                    @case(3)
                        Divorciado
                        @break
                @endswitch
            </td>
        </tr>
        <tr>
            <th scope="row">Data Nasc.</th>
            <td>{{$cliente->date_birth}}</td>
        </tr>
        <tr>
            <th scope="row">Sexo</th>
            <td>{{$cliente->sex == 'm' ? 'Masculino': 'Feminino'}}</td>
        </tr>
        <tr>
            <th scope="row">Def. Física</th>
            <td>{{$cliente->physical_disability}}</td>
        </tr>
        <tr>
            <th scope="row">Inadimplente</th>
            <td>{{$cliente->defaulter?'Sim': 'Não'}}</td>
        </tr>
        </tbody>
    </table>
@endsection

resources/views/admin/form/_form_errors.blade.php
@if($errors->any())
<div class="container">
    <div class="row">
        <div class="col-md">
            <ul class="alert alert-danger">
                @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach  
            </ul>
        </div>
        
    </div>
</div>

@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel bg-dark ">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @section('navbar')
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @show
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/layout.blade.php
<html>
<head>
    <link rel="stylesheet" href="/css/app.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body>
<div class="row">
    <div class="container-fluid">
        <h1 class="text-center">Laravel: Formulários e Validações</h1>
        @yield('content')
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type="text/javascript" src="/js/app.js"></script>
</body>
</html>